apiVersion: 1

datasources:
  - name: Akvorado ClickHouse
    type: grafana-clickhouse-datasource
    uid: akvorado_clickhouse
    access: proxy
    url: http://clickhouse:8123
    jsonData:
      defaultDatabase: akvorado
      username: akvorado
      protocol: http
      port: 8123
      server: clickhouse
      path: ""
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsSkipVerify: false
    secureJsonData:
      password: akvorado123
    isDefault: true
    editable: true
